version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    # image : plexinc/pms-docker
    container_name: plex
    network_mode: bridge
    ports:
        - "32400:32400" # (for access to the Plex Media Server) [required]
        - "3005:3005" # (for controlling Plex Home Theater via Plex Companion)
        - "8324:8324" # (for controlling Plex for Roku via Plex Companion)
        - "32410:32410/udp" # (for current GDM network discovery)
        - "32412:32412/udp" # (for current GDM network discovery)
        - "32413:32413/udp" # (for current GDM network discovery)
        - "32414:32414/udp" # (for current GDM network discovery)
        - "32469:32469" # (for access to the Plex DLNA Server)
        - "32401:32401"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= claim-yZ1jitbkSd7yk5U1bKTs
    volumes:
      - ./config:/config
      - ./customPlugins:/config/Library/Plug-ins
      - /Volumes/Toshiba:/data
    restart: unless-stopped
